spring:
  kafka:
    bootstrap-servers: broker:29092
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
