spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: togrul
    password: password
    url: jdbc:postgresql://localhost:5432/order_service
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8586
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka