spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://togrul:password@localhost:27017/product?authSource=admin
server:
  port: 8585
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
