spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: togrul
    password: password
    url: jdbc:postgresql://localhost:5432/inventory_service
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8587